export type GlossaryCategory = 'acronym' | 'kpi' | 'term';

export interface GlossaryEntry {
  term: string;
  category: GlossaryCategory;
  definition: string;
  // Only present on `kpi` entries. Some KPIs are raw counts, direct time
  // measurements, or platform-proprietary composite indices rather than a
  // clean ratio — the string says so honestly instead of forcing a fake formula.
  formula?: string;
}

// Every marketing term, acronym, and performance/analytics KPI referenced
// across the app (Analytics, Ads, SEO, Email/SMS, Social, Content, Monitoring,
// Cart Recovery, Alerts). Kept alphabetical by `term`.
export const GLOSSARY: GlossaryEntry[] = [
  { term: '301 Redirect', category: 'term', definition: 'A permanent server-side redirect from one URL to another. Search engines pass most of the original page’s ranking value through a single 301 hop.' },
  { term: '404 Error', category: 'term', definition: 'The response returned when a requested page no longer exists. Internal links or backlinks pointing to a 404 waste crawl budget and lose visitors.' },
  { term: 'A/B Test', category: 'term', definition: 'An experiment that splits traffic between two variants — ad creative, subject line, page copy — to see which performs better before rolling out the winner.' },
  { term: 'Abandonment Rate', category: 'kpi', definition: 'Share of shoppers who add items to a cart but leave without completing checkout. The inverse of your cart conversion rate.', formula: '(Carts Abandoned ÷ Carts Created) × 100' },
  { term: 'Acceptance Rate', category: 'kpi', definition: 'Percentage of recipients who complete a requested action, such as accepting an SMS opt-in or a suggested change.', formula: '(Actions Accepted ÷ Total Prompted) × 100' },
  { term: 'Ad Frequency', category: 'kpi', definition: 'Average number of times a single user sees the same ad within a given period. Rising frequency without new creative signals ad fatigue.', formula: 'Impressions ÷ Reach (unique users)' },
  { term: 'Ad Group / Ad Set', category: 'term', definition: 'A collection of ads within a campaign that share the same targeting, budget, and bidding settings. Google calls it an “ad group”, Meta an “ad set”.' },
  { term: 'Ad Spend', category: 'kpi', definition: 'Total amount paid to run advertising across all channels in a given period, before factoring in the revenue it produced.', formula: 'Sum of spend across all ad platforms in the period — a total, not a ratio.' },
  { term: 'Anchor Text', category: 'term', definition: 'The clickable, visible text of a hyperlink. Search engines use it as a relevance signal for the page being linked to.' },
  { term: 'API', category: 'acronym', definition: 'Application Programming Interface — the interface that lets this app pull data from and push actions to external platforms like Shopify, Meta, or Google.' },
  { term: 'Attribution Model', category: 'term', definition: 'The rule set that decides how credit for a conversion is split across the marketing touchpoints a customer interacted with (see First-Touch, Last-Touch, Linear, and Position-Based attribution).' },
  { term: 'Average Order Value (AOV)', category: 'kpi', definition: 'Total revenue divided by number of orders. A rising AOV means customers are buying more per transaction.', formula: 'Total Revenue ÷ Number of Orders' },
  { term: 'B2B', category: 'acronym', definition: 'Business-to-Business — marketing or sales motions aimed at other companies rather than individual consumers.' },
  { term: 'Benchmark', category: 'term', definition: 'A reference performance figure — often an industry or historical average — used to judge whether a metric is good or bad in context.' },
  { term: 'Blended CPA', category: 'kpi', definition: 'Cost Per Acquisition averaged across every paid channel combined, rather than reported per-channel.', formula: 'Total Ad Spend (all channels) ÷ Total Conversions (all channels)' },
  { term: 'Blended ROAS', category: 'kpi', definition: 'Return on Ad Spend calculated across all paid channels together, giving one overall efficiency number for total ad spend.', formula: 'Total Revenue (all channels) ÷ Total Ad Spend (all channels)' },
  { term: 'Bounce Rate', category: 'kpi', definition: 'Percentage of visitors who leave a site after viewing only one page with no further interaction.', formula: '(Single-Page Sessions ÷ Total Sessions) × 100' },
  { term: 'Brand Mentions', category: 'term', definition: 'Instances where your brand name is referenced across the web or social platforms, tracked whether or not the mention links back to your site.' },
  { term: 'Brand Voice', category: 'term', definition: 'The consistent tone, vocabulary, and personality a brand uses across its content and copy.' },
  { term: 'Budget Pacing', category: 'term', definition: 'How evenly — or aggressively — a campaign’s budget is being spent relative to the time elapsed in its flight.' },
  { term: 'Budget Utilization', category: 'kpi', definition: 'Percentage of an allocated budget that has actually been spent, used to flag campaigns at risk of under- or over-spending.', formula: '(Spend to Date ÷ Allocated Budget) × 100' },
  { term: 'Canonical Tag', category: 'term', definition: 'An HTML tag (rel="canonical") that tells search engines which URL is the “master” version of duplicate or near-duplicate pages.' },
  { term: 'Capture Rate', category: 'kpi', definition: 'Percentage of eligible visitors who convert into a captured contact, such as an email or SMS signup, at a given touchpoint.', formula: '(Contacts Captured ÷ Eligible Visitors) × 100' },
  { term: 'Cart Value', category: 'kpi', definition: 'Total dollar value of items sitting in a customer’s cart. Used to size the opportunity behind abandoned-cart recovery.', formula: 'Σ (item price × quantity) across all items currently in the cart' },
  { term: 'Channel Attribution', category: 'term', definition: 'Assigning conversion credit to the specific marketing channel or channels that contributed to a sale.' },
  { term: 'Churn', category: 'kpi', definition: 'The rate at which customers or subscribers stop engaging or unsubscribe over a given period.', formula: '(Customers Lost in Period ÷ Customers at Start of Period) × 100' },
  { term: 'Click Rate', category: 'kpi', definition: 'Percentage of message or email recipients who click a link inside it.', formula: '(Clicks ÷ Messages Delivered) × 100' },
  { term: 'Click-Through Rate (CTR)', category: 'kpi', definition: 'Clicks divided by impressions. Measures how compelling an ad, link, or subject line is at earning a click.', formula: '(Clicks ÷ Impressions) × 100' },
  { term: 'Complaint Rate', category: 'kpi', definition: 'Percentage of email recipients who mark a message as spam. High rates damage sender reputation and future deliverability.', formula: '(Spam Complaints ÷ Emails Delivered) × 100' },
  { term: 'Conversion Funnel', category: 'term', definition: 'The staged path visitors take from first touch to purchase (visit → add to cart → checkout → purchase), used to spot where prospects drop off.' },
  { term: 'Conversion Rate (CVR)', category: 'kpi', definition: 'Percentage of visitors or leads who complete a desired action, such as a purchase or signup.', formula: '(Conversions ÷ Visitors or Sessions) × 100' },
  { term: 'Core Web Vitals (CWV)', category: 'acronym', definition: 'Google’s page-experience metrics — Largest Contentful Paint, Cumulative Layout Shift, and First Input Delay — used as an SEO ranking signal.' },
  { term: 'Cost Per Acquisition (CPA)', category: 'kpi', definition: 'Total ad spend divided by the number of conversions it produced. Lower is more efficient.', formula: 'Ad Spend ÷ Conversions' },
  { term: 'Cost Per Click (CPC)', category: 'kpi', definition: 'The average amount paid each time someone clicks a paid ad.', formula: 'Ad Spend ÷ Clicks' },
  { term: 'Crawl / Crawler', category: 'term', definition: 'The process by which search-engine bots discover and read pages on a site. Crawl errors can block a page from being indexed at all.' },
  { term: 'Creative', category: 'term', definition: 'The actual ad asset shown to users — image, video, or copy — as opposed to its targeting or budget settings.' },
  { term: 'CRM', category: 'acronym', definition: 'Customer Relationship Management — software used to track and manage interactions with leads and customers.' },
  { term: 'Customer Lifetime Value (CLV / LTV)', category: 'kpi', definition: 'Total revenue a business expects to earn from a customer across the entire relationship.', formula: 'Average Order Value × Purchase Frequency × Average Customer Lifespan' },
  { term: 'Delivery Rate', category: 'kpi', definition: 'Percentage of sent emails or SMS messages that actually reach a recipient’s inbox rather than bouncing.', formula: '(Messages Delivered ÷ Messages Sent) × 100' },
  { term: 'Duplicate Content', category: 'term', definition: 'Substantially identical content accessible at more than one URL, which can split ranking signals and confuse search engines about which version to index.' },
  { term: 'Email Deliverability', category: 'kpi', definition: 'The overall health of an email program’s ability to land in the inbox, factoring in delivery, bounce, and complaint rates together.', formula: 'Weighted composite of Delivery Rate, Bounce Rate, and Complaint Rate — not a single ratio.' },
  { term: 'Engagement Rate', category: 'kpi', definition: 'Interactions (likes, comments, shares, replies) divided by reach or followers, showing how actively an audience responds to content.', formula: '(Likes + Comments + Shares + Replies) ÷ Reach or Followers × 100' },
  { term: 'Engagement Score', category: 'kpi', definition: 'A composite index summarizing how actively an audience or subscriber list interacts with your content over time.', formula: 'Weighted composite of engagement rate, frequency, and recency signals normalized to an index — not a single ratio.' },
  { term: 'First Input Delay (FID)', category: 'acronym', definition: 'A Core Web Vitals metric measuring the delay between a user’s first interaction with a page and the browser actually responding.' },
  { term: 'First-Touch Attribution', category: 'term', definition: 'An attribution model that gives 100% of the conversion credit to the very first channel in a customer’s path.' },
  { term: 'Frequency Cap', category: 'term', definition: 'A limit on how many times a single user can be shown the same ad within a set time window, used to prevent ad fatigue.' },
  { term: 'GA4', category: 'acronym', definition: 'Google Analytics 4 — Google’s event-based web analytics platform used to measure traffic and on-site behavior.' },
  { term: 'GBP (Google Business Profile)', category: 'acronym', definition: 'The free listing that controls how a business appears in Google Search and Maps, including hours, reviews, and photos.' },
  { term: 'GSC (Google Search Console)', category: 'acronym', definition: 'Google’s free tool for monitoring a site’s search performance, indexing status, and technical SEO issues.' },
  { term: 'Health Score', category: 'term', definition: 'A composite 0–100 score summarizing the overall condition of a store, page, or campaign across several weighted signals.' },
  { term: 'Heading Hierarchy (H1/H2/H3)', category: 'term', definition: 'The nested structure of heading tags on a page. A clear, single-H1 hierarchy helps both readers and search engines understand page structure.' },
  { term: 'Impressions', category: 'kpi', definition: 'The number of times an ad, post, or page was displayed, regardless of whether it was clicked.', formula: 'Raw count of displays — a count, not a ratio.' },
  { term: 'Keyword Density', category: 'term', definition: 'How often a target keyword appears relative to a page’s total word count. Too low under-signals relevance; too high risks looking like keyword stuffing.' },
  { term: 'Keyword Difficulty', category: 'kpi', definition: 'A score estimating how hard it would be to rank on the first page of search results for a given keyword.', formula: 'Weighted score derived from the authority/backlink strength of pages already ranking in the top 10 — a modeled index, not a simple ratio.' },
  { term: 'Keyword Rank / Position', category: 'kpi', definition: 'A keyword’s current placement in search engine results pages, typically tracked over time to show movement.', formula: 'Ordinal position (1st, 2nd, 3rd…) of a URL in search results for a given keyword — a rank, not a ratio.' },
  { term: 'KPI', category: 'acronym', definition: 'Key Performance Indicator — any metric chosen to measure progress toward a specific business or campaign goal.' },
  { term: 'Largest Contentful Paint (LCP)', category: 'acronym', definition: 'A Core Web Vitals metric measuring how long it takes for the largest visible element on a page to finish rendering.' },
  { term: 'Last-Touch Attribution', category: 'term', definition: 'An attribution model that gives 100% of the conversion credit to the final channel a customer interacted with before converting.' },
  { term: 'Lead Gen', category: 'term', definition: 'Lead Generation — marketing activity focused on capturing contact information from prospective customers for later follow-up.' },
  { term: 'Linear Attribution', category: 'term', definition: 'An attribution model that splits conversion credit equally across every touchpoint in a customer’s path.' },
  { term: 'Load Speed', category: 'kpi', definition: 'How quickly a page finishes rendering for a visitor, commonly proxied by Largest Contentful Paint.', formula: 'Elapsed time from navigation start to the page becoming visually complete — a direct time measurement, not a ratio.' },
  { term: 'Lookalike Audience', category: 'term', definition: 'A targeting audience an ad platform generates by finding new users who share traits with an existing customer list.' },
  { term: 'Meta Description', category: 'term', definition: 'The short HTML summary of a page shown beneath its title in search results. It doesn’t affect rankings directly but strongly influences click-through rate.' },
  { term: 'Mobile-First Indexing', category: 'term', definition: 'Google’s practice of primarily using a site’s mobile version for indexing and ranking, making mobile page quality a direct SEO factor.' },
  { term: 'Open Graph (OG) Tags', category: 'term', definition: 'HTML metadata that controls how a page’s title, description, and image appear when shared on social platforms.' },
  { term: 'Open Rate', category: 'kpi', definition: 'Percentage of email recipients who open a given message, used as a proxy for subject-line and sender-reputation strength.', formula: '(Emails Opened ÷ Emails Delivered) × 100' },
  { term: 'Organic Traffic', category: 'term', definition: 'Visitors who arrive at a site through unpaid search engine results, as opposed to paid ads, social, or direct traffic.' },
  { term: 'Orphan Page', category: 'term', definition: 'A page with no internal links pointing to it, making it hard for both users and search engine crawlers to discover.' },
  { term: 'Pageviews', category: 'kpi', definition: 'The total number of pages loaded by visitors, including repeat views of the same page by the same person.', formula: 'Raw count of page loads, including repeat views — a count, not a ratio.' },
  { term: 'Performance Score', category: 'kpi', definition: 'A composite rating — often used for ad creative or content — that rolls several individual metrics into one overall grade.', formula: 'Weighted average of sub-scores (e.g. Clarity, Emotional Appeal, CTA Strength, Brand Alignment), each normalized to 0–100.' },
  { term: 'Position-Based Attribution', category: 'term', definition: 'An attribution model that gives 40% credit to the first touchpoint, 40% to the last, and splits the remaining 20% across the touchpoints in between.' },
  { term: 'Quality Score', category: 'kpi', definition: 'A platform’s rating of an ad’s expected relevance and performance, which influences both ad rank and cost per click.', formula: 'Platform-proprietary weighted composite of expected CTR, ad relevance, and landing page experience — not independently calculable from a single formula.' },
  { term: 'Reach', category: 'kpi', definition: 'The number of unique people who saw a piece of content or an ad, as distinct from impressions which can count repeat views.', formula: 'Raw count of unique viewers — a count, not a ratio.' },
  { term: 'Recovery Rate', category: 'kpi', definition: 'Percentage of abandoned carts that are successfully brought back to complete a purchase, typically via email or SMS follow-up.', formula: '(Abandoned Carts Recovered ÷ Total Abandoned Carts) × 100' },
  { term: 'Remarketing / Retargeting', category: 'term', definition: 'Showing ads specifically to people who have already visited your site or engaged with your brand, to bring them back to convert.' },
  { term: 'Repeat Purchase Rate', category: 'kpi', definition: 'Percentage of customers who make more than one purchase, a core indicator of retention and loyalty.', formula: '(Customers with 2+ Orders ÷ Total Customers) × 100' },
  { term: 'Response Time', category: 'kpi', definition: 'How long a server takes to respond to a request, tracked as a core site-health and uptime indicator.', formula: 'Elapsed time between a request being sent and the server’s first response byte — a direct time measurement, not a ratio.' },
  { term: 'Return on Ad Spend (ROAS)', category: 'kpi', definition: 'Revenue generated for every dollar spent on advertising, expressed as a multiple (e.g. 4.2×).', formula: 'Revenue ÷ Ad Spend' },
  { term: 'Return on Investment (ROI)', category: 'kpi', definition: 'Net profit from an activity divided by its cost, expressed as a percentage. Broader than ROAS since it can account for margin, not just revenue.', formula: '((Revenue − Cost) ÷ Cost) × 100' },
  { term: 'Robots.txt', category: 'term', definition: 'A file at a site’s root that tells search engine crawlers which pages or sections they are allowed to crawl.' },
  { term: 'Schema Markup / Structured Data', category: 'term', definition: 'Standardized code (e.g. JSON-LD) added to a page that helps search engines understand its content and can unlock rich results like star ratings.' },
  { term: 'Search Volume', category: 'kpi', definition: 'The average number of times a keyword is searched in a given period, used to gauge demand before targeting it.', formula: 'Raw average count of searches over a period (e.g. monthly) — a count, not a ratio.' },
  { term: 'Sentiment Analysis', category: 'term', definition: 'Automated classification of text — reviews, comments, mentions — as positive, negative, or neutral in tone.' },
  { term: 'SEO', category: 'acronym', definition: 'Search Engine Optimization — the practice of improving a site’s visibility in unpaid search engine results.' },
  { term: 'SERP', category: 'acronym', definition: 'Search Engine Results Page — the page of results a search engine shows for a given query, including organic listings, ads, and rich features.' },
  { term: 'Session', category: 'kpi', definition: 'A single period of activity by one visitor on a site, which can include multiple pageviews before it times out.', formula: 'A defined unit (activity bounded by a period of inactivity, commonly 30 minutes), not a calculated ratio.' },
  { term: 'Sitemap', category: 'term', definition: 'An XML file listing a site’s pages to help search engines discover and prioritize them for crawling.' },
  { term: 'SKU', category: 'acronym', definition: 'Stock Keeping Unit — a unique identifier for a distinct, sellable product or variant.' },
  { term: 'SMS', category: 'acronym', definition: 'Short Message Service — text messaging used as a marketing channel for cart recovery, promotions, and alerts.' },
  { term: 'SSL', category: 'acronym', definition: 'Secure Sockets Layer — the certificate technology that encrypts traffic to a site (shown as the padlock/HTTPS in a browser) and is also a minor SEO ranking factor.' },
  { term: 'Thin Content', category: 'term', definition: 'Pages with little substantive text or unique value, which search engines tend to rank poorly compared to more comprehensive competing pages.' },
  { term: 'Title Tag', category: 'term', definition: 'The HTML element defining a page’s title, shown as the clickable headline in search results and browser tabs. A key on-page SEO signal.' },
  { term: 'Top 3 / Top 10 Rankings', category: 'kpi', definition: 'The count of tracked keywords currently ranking within the first 3 or first 10 search results, a common proxy for overall SEO health.', formula: 'Count of tracked keywords where Keyword Rank ≤ 3 (or ≤ 10)' },
  { term: 'UGC', category: 'acronym', definition: 'User-Generated Content — photos, reviews, or posts created by customers rather than the brand, often reused in ads for authenticity.' },
  { term: 'Unsubscribe Rate', category: 'kpi', definition: 'Percentage of recipients who opt out of a mailing list after a given send.', formula: '(Unsubscribes ÷ Emails Delivered) × 100' },
  { term: 'Upsell Value', category: 'kpi', definition: 'Additional revenue generated by encouraging a customer to buy a higher-tier or add-on product during their purchase.', formula: 'Additional Revenue from Upsold Items ÷ Orders Containing an Upsell' },
  { term: 'Uptime', category: 'kpi', definition: 'The percentage of time a site or service is available and responding normally, typically tracked over a rolling window (e.g. 7 days).', formula: '(Time Available ÷ Total Time in Period) × 100' },
  { term: 'UTM Parameters', category: 'acronym', definition: 'Tags appended to a URL (source, medium, campaign, etc.) that let analytics tools attribute traffic and conversions to a specific marketing link.' },
];

export const GLOSSARY_CATEGORY_LABELS: Record<GlossaryCategory, string> = {
  acronym: 'Acronym',
  kpi: 'KPI',
  term: 'Term',
};
